name: CI
on:
  pull_request:
    branches:
      - 'master'
  push:
    tags:
      - "*"
    branches:
      - 'master'

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      
      # - name: Grant Permission to Execute
      #  run: chmod +x gradlew
        
      # - name: Unit tests
      #  run: bash ./gradlew test --stacktrace

  apk:
    name: Generate APK
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grant Permission to Execute
        run: chmod +x gradlew
        
      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace
        
      - name: Upload APK to Github Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
          
      - name: Upload to Github Releases with release tags
        uses: docker://antonyurchenko/git-release:latest
        with:
          args: |
            app/build/outputs/apk/debug/app-debug.apk
        env:  
          ALLOW_EMPTY_CHANGELOG: "true"
          ALLOW_TAG_PREFIX: "true"
          RELEASE_NAME_PREFIX: "Release "
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_RELEASE }}
          
      - name: Distribute to AppCenter
        uses: devussy/AppCenter-Distribute-Github-Action@v1.0.2
        with:
          app: wajahatkarim3/pandemic
          token: ${{secrets.APP_CENTER_TOKEN}}
          group: public
          file: app/build/outputs/apk/debug/app-debug.apk
          silent: false
